### ISSUE TITLE
ajito.vgの今後

### ISSUE THREAD

**Issue by tomill** [voyagegroup/ajito#8]
**現時点の情報**

* ドメイン [ajito.vg](http://ajito.vg/) / valuedomain 冨田個人アカウント
* 2015-05-19 に切れる
* 更新費用 10584円
* ソース https://github.com/tomill/ajito.vg
* デプロイ先 冨田の個人サーバー
* ajiting写真を取ってくるところ http://ajiting.tumblr.com/ 利用。小芝さん作。クローラが止まってしまったとのこと

そうとうまえ衆さんにいらない？きいたけど興味無さげだった。今はカルチャーサイトあるしねえ〜

**Comment by tomill** [comment]
案

* 捨てる → ドメイン生きているうちに http://culture.voyagegroup.com/environment/ajito とかにリダイレクト入れてしまうのが良いと思う
* 更新する → ajiting会会長（仮）小賀さんに売却できないものか
* 更新する → カンパ？
* 更新する → みんながいじれるサーバーにあげる、とかも検討

**Comment by hironomiu-vg** [comment]
これVOYAGE GROUPのブランディングとして使い道あると思うのでERDGで引き取れないか検討します。

2015年3月24日 20:50 Naoki Tomita <notifications@github.com>:

**Comment by awa-vg** [comment]
今 .vg って更新以外なんもできない気がします

**Comment by tomill** [comment]
三浦さんとこで引き取って使ってもらえることになりました。新生 ajito.vg にご期待ください :)
